project:
  type: website

website:
  title: "New Approaches and Data Sources to Study Digital Media and Democracy"
  site-url: "https://digidem_ic2s2.github.io"
  search: False
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: index.qmd#program
        text: Program
      - href: index.qmd#speakers
        text: Speakers
      - href: index.qmd#organizers
        text: Organizers

format:
  html:
    theme: [cosmo,custom.scss]
    fontsize: "1.5em"
    page-layout: full
    css: styles.css
    toc: true

execute:
  freeze: auto

